apiVersion: v1
kind: Service
metadata:
  name: crd-conversion-webhook
  namespace: crossplane-system
spec:
  ports:
  - name: tls
    port: 443
    targetPort: tls
  selector:
     name: crd-conversion-webhook
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crd-conversion-webhook
  namespace: crossplane-system
  labels:
    name: crd-conversion-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      name: crd-conversion-webhook
  template:
    metadata:
      labels:
        name: crd-conversion-webhook
    spec:
      containers:
       - name: crd-conversion-webhook
         image: haarchri/xrd-webhook:v0.1.0
         command:
         - /xrd-webhook
         args:
           - -tls-cert-file=/etc/webhook/certs/cert.pem
           - -tls-private-key-file=/etc/webhook/certs/key.pem
         ports:
         - name: tls
           containerPort: 443
         volumeMounts:
           - name: webhook-certs
             mountPath: /etc/webhook/certs
             readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: crd-conversion-webhook.crossplane-system.svc